name: Build and Release Cross-Platform Binaries

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        include:
          - arch: amd64
            runner_arch: x86_64

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make gcc g++ libssl-dev libnss3-dev libnspr4-dev

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_NOTHING_BY_DEFAULT=0

      - name: Build binaries
        run: |
          cd build
          make -j8

      - name: Package binaries
        run: |
          cd build
          mkdir out
          cp server/badvpn-server out/ || true
          cp client/badvpn-client out/ || true
          cp tun2socks/badvpn-tun2socks out/ || true
          cp udpgw/badvpn-udpgw out/ || true
          tar czvf badvpn-${{ matrix.arch }}-linux.tar.gz out

      - uses: actions/upload-artifact@v4
        with:
          name: badvpn-${{ matrix.arch }}-linux
          path: build/badvpn-${{ matrix.arch }}-linux.tar.gz

  release:
    name: Release
    needs: [build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: workflow_${{github.run_number}}
          name: Release ${{github.run_number}}
          token: ${{secrets.GH_TOKEN}}
          files: |
            artifacts/badvpn-amd64-linux/badvpn-amd64-linux.tar.gz
